In [1]:
import numpy as np

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
import keras

Using TensorFlow backend.


In [3]:
odd_nums = np.array([1,3,5,7,9,11,13])

# run a window of size 2 over the odd number sequence and display the results
window_size = 2

X = []
X.append(odd_nums[0:2])
X.append(odd_nums[1:3])
X.append(odd_nums[2:4])
X.append(odd_nums[3:5])
X.append(odd_nums[4:6])

y = odd_nums[2:]

X = np.asarray(X)
y = np.asarray(y)
y = np.reshape(y, (len(y),1)) #optional

assert(type(X).__name__ == 'ndarray')
assert(type(y).__name__ == 'ndarray')
assert(X.shape == (5,2))
assert(y.shape in [(5,1), (5,)])

# print out input/output pairs --> here input = X, corresponding output = y
print ('--- the input X will look like ----')
print (X)

print ('--- the associated output y will look like ----')
print (y)

--- the input X will look like ----
[[ 1  3]
 [ 3  5]
 [ 5  7]
 [ 7  9]
 [ 9 11]]
--- the associated output y will look like ----
[[ 5]
 [ 7]
 [ 9]
 [11]
 [13]]


In [48]:
start = 0
window_size = 2
print (range(len(odd_nums) - window_size))
X = [odd_nums[start:start + window_size] 
     for start in range(len(odd_nums) - window_size)]
X = np.asarray(X)
print(X)
y = [odd_nums[start:start+1] for start in range(window_size, len(odd_nums))]
print(np.asarray(y))

range(0, 5)
[[ 1  3]
 [ 3  5]
 [ 5  7]
 [ 7  9]
 [ 9 11]]
[[ 5]
 [ 7]
 [ 9]
 [11]
 [13]]


In [51]:
# TODO: fill out the function below that transforms the input series 
# and window-size into a set of input/output pairs for use with our RNN model
def window_transform_series(series, window_size):
    # containers for input/output pairs
    X = []
    y = []
    
    series_size = len(series)
    X = [series[start:start + window_size] 
         for start in range(series_size - window_size)]
    y = [series[start] for start in range(window_size, series_size)]

    # reshape each 
    X = np.asarray(X)
    X.shape = (np.shape(X)[0:2])
    y = np.asarray(y)
    y.shape = (len(y),1)

    return X,y



In [59]:
X, y = window_transform_series(odd_nums, 6)
print (X)
print (y)

[[ 1  3  5  7  9 11]]
[[13]]


In [60]:
### TODO: fill out the function below that transforms the input text and window-size into a set of input/output pairs for use with our RNN model
def window_transform_text(text, window_size, step_size):
    # containers for input/output pairs
    inputs = []
    outputs = []
    
    text_size = len(text)
    inputs = [text[start:start+window_size]
             for start in range(text_size - window_size, step=step_size)]
    outputs = [text[start]
               for start in range(window_size, text_size, step=step_size)]

    return inputs,outputs

In [24]:
def cleaned_text(text):
    from string import ascii_lowercase

    text = text.lower()

    punctuation = ['!', ',', '.', ':', ';', '?']
    valid_chars = list(ascii_lowercase) + punctuation
    for c in text: 
        if c not in valid_chars:
            text = text.replace(c, " ")
    return text

In [25]:
print (cleaned_text("the rain in spain FALLS mainly\non\nthe\[plain]"))

the rain in spain falls mainly on the  plain 
